all:
	cd ./src/video_get;make
	cd ./src/video_preprocess;make
	cd ./src/video_process;make
	cd ./src/order_send;make

	

clean: 
	cd ./src/video_get;make clean
	cd ./src/video_preprocess;make clean
	cd ./src/video_process;make clean
	cd ./src/order_send;make clean
